Update Harness.js
acuminous/zUnit pull request #3
Opened 2021-01-17 17:39 UTC by Code-Science

Broke down run function into separate functions

2021-01-20 09:43 UTC, cressie176 requested changes
Thanks for the PR.  I think there's one small mistake, but otherwise looks good.

2021-01-20 09:43 UTC, cressie176 commented on lib/Harness.js
> -
I think you meant to return the options, e.g.
```js
return this._options.apply(runtimeOptions);
```

2021-01-20 10:50 UTC, Code-Science commented
Sorry about that, i forgot to return the options. I just updated the file. Hope it looks fine now.

2021-01-27 08:14 UTC, cressie176 commented
Thanks @Code-Science, I merged locally and have pushed to main. Not sure why GitHub didn't close the PR. I probably missed a command.

2021-01-27 08:14 UTC, closed without merging